development:
  host: 198.245.51.73
  port: 27018
  database: grouponer_development

test:
  host: 198.245.51.73
  port: 27018
  database: grouponer_test

# set these environment variables on your prod server
production:
  host: 127.0.0.1
  port: 27018
  #username: <%= ENV['MONGOID_USERNAME'] %>
  #password: <%= ENV['MONGOID_PASSWORD'] %>
  database: grouponer_development
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
